const bankList = [
  "Ally Bank",
  "American Express National Bank",
  "Axos Bank",
  "BancorpSouth Bank",
  "Bank of America",
  "Bank of Hawaii",
  "Bank of Marin",
  "Bank of New York Mellon",
  "BB&T",
  "BBVA USA",
  "BMO Harris Bank",
  "BOK Financial",
  "Cadence Bank",
  "Capital One",
  "Cathay Bank",
  "Charles Schwab Bank",
  "Chime",
  "CIBC Bank USA",
  "CIT Bank",
  "Citibank",
  "City National Bank",
  "Comerica Bank",
  "ConnectOne Bank",
  "Discover Bank",
  "East West Bank",
  "Fifth Third Bank",
  "First Citizens Bank",
  "First Horizon Bank",
  "First National Bank of Pennsylvania",
  "First Republic Bank",
  "First United Bank",
  "Flagstar Bank",
  "Frost Bank",
  "Goldman Sachs Bank USA",
  "Home Savings Bank",
  "Huntington Bank",
  "JPMorgan Chase",
  "KeyBank",
  "Live Oak Bank",
  "M&T Bank",
  "Marcus by Goldman Sachs",
  "MidFirst Bank",
  "Navy Federal Credit Union",
  "New York Community Bank",
  "North Shore Bank",
  "Northpointe Bank",
  "Northwest Bank",
  "OceanFirst Bank",
  "Old National Bank",
  "OneWest Bank",
  "PNC Bank",
  "Popular Direct",
  "Popular, Inc.",
  "Prime Alliance Bank",
  "Quontic Bank",
  "Radius Bank",
  "Regions Bank",
  "Rockland Trust",
  "Santander Bank",
  "Seacoast Bank",
  "Signature Bank",
  "Simmons Bank",
  "Simple",
  "South State Bank",
  "State Farm Bank",
  "Sterling National Bank",
  "SunTrust Bank",
  "Synchrony Bank",
  "TCF Bank",
  "TD Bank",
  "The Bank of Glen Burnie",
  "The Huntington National Bank",
  "Trustmark National Bank",
  "U.S. Bank",
  "Union Bank",
  "United Community Bank",
  "United Midwest Savings Bank",
  "USAA",
  "Valley National Bank",
  "Wells Fargo",
  "Westamerica Bank",
  "Wintrust Bank",
  "Zions Bank",
];

export const europeanBanks = [
  "ABN AMRO",
  "Alpha Bank",
  "Banco BPM",
  "Banco de Sabadell",
  "Banco Santander",
  "Bank of Cyprus",
  "Bank of Ireland",
  "Bankinter",
  "Barclays",
  "Belfius",
  "BGL BNP Paribas",
  "BNP Paribas",
  "BPER Banca",
  "CaixaBank",
  "Commerzbank",
  "Crédit Agricole",
  "Crédit Mutuel",
  "Credit Suisse",
  "Danske Bank",
  "Deutsche Bank",
  "DNB ASA",
  "Erste Group Bank",
  "Eurobank",
  "Handelsbanken",
  "HSBC",
  "HypoVereinsbank",
  "ING Group",
  "Intesa Sanpaolo",
  "Jyske Bank",
  "KBC Group",
  "La Banque Postale",
  "Landesbank Baden-Württemberg",
  "Lloyds Banking Group",
  "Mediobanca",
  "Monzo Bank",
  "N26",
  "Nationwide Building Society",
  "NatWest Group",
  "Nordea",
  "Piraeus Bank",
  "Raiffeisen Bank International",
  "Revolut",
  "SEB Group",
  "Skandinaviska Enskilda Banken (SEB)",
  "Société Générale",
  "SpareBank 1",
  "Swedbank",
  "UBS",
  "UniCredit",
  "Virgin Money",
  "Volksbank",
];

export const australianBanks = [
  "AMP Bank",
  "ANZ (Australia and New Zealand Banking Group)",
  "Bank Australia",
  "Bank of Queensland",
  "BankSA",
  "Bankwest",
  "Bendigo and Adelaide Bank",
  "Commonwealth Bank of Australia",
  "Defence Bank",
  "Heritage Bank",
  "ING Australia",
  "Macquarie Bank",
  "ME Bank (Members Equity Bank)",
  "NAB (National Australia Bank)",
  "People's Choice Credit Union",
  "Rabobank Australia",
  "St.George Bank",
  "Suncorp Bank",
  "Teachers Mutual Bank",
  "UBank",
  "Westpac",
];

export { bankList };
