const bankList = [
	'Ally Bank',
	'American Express National Bank',
	'Axos Bank',
	'BancorpSouth Bank',
	'Bank of America',
	'Bank of Hawaii',
	'Bank of Marin',
	'Bank of New York Mellon',
	'BB&T',
	'BBVA USA',
	'BMO Harris Bank',
	'BOK Financial',
	'Cadence Bank',
	'Capital One',
	'Cathay Bank',
	'Charles Schwab Bank',
	'Chime',
	'CIBC Bank USA',
	'CIT Bank',
	'Citibank',
	'City National Bank',
	'Comerica Bank',
	'ConnectOne Bank',
	'Discover Bank',
	'East West Bank',
	'Fifth Third Bank',
	'First Citizens Bank',
	'First Horizon Bank',
	'First National Bank of Pennsylvania',
	'First Republic Bank',
	'First United Bank',
	'Flagstar Bank',
	'Frost Bank',
	'Goldman Sachs Bank USA',
	'Home Savings Bank',
	'Huntington Bank',
	'JPMorgan Chase',
	'KeyBank',
	'Live Oak Bank',
	'M&T Bank',
	'Marcus by Goldman Sachs',
	'MidFirst Bank',
	'Navy Federal Credit Union',
	'New York Community Bank',
	'North Shore Bank',
	'Northpointe Bank',
	'Northwest Bank',
	'OceanFirst Bank',
	'Old National Bank',
	'OneWest Bank',
	'PNC Bank',
	'Popular Direct',
	'Popular, Inc.',
	'Prime Alliance Bank',
	'Quontic Bank',
	'Radius Bank',
	'Regions Bank',
	'Rockland Trust',
	'Santander Bank',
	'Seacoast Bank',
	'Signature Bank',
	'Simmons Bank',
	'Simple',
	'South State Bank',
	'State Farm Bank',
	'Sterling National Bank',
	'SunTrust Bank',
	'Synchrony Bank',
	'TCF Bank',
	'TD Bank',
	'The Bank of Glen Burnie',
	'The Huntington National Bank',
	'Trustmark National Bank',
	'U.S. Bank',
	'Union Bank',
	'United Community Bank',
	'United Midwest Savings Bank',
	'USAA',
	'Valley National Bank',
	'Wells Fargo',
	'Westamerica Bank',
	'Wintrust Bank',
	'Zions Bank'
];

export { bankList };
